// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: order.proto

package server

import (
	"context"

	"github.com/tsfdsong/tradeengin/app/order/internal/logic"
	"github.com/tsfdsong/tradeengin/app/order/internal/svc"
	"github.com/tsfdsong/tradeengin/app/order/order"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *order.OrderRequest) (*order.OrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServiceServer) CreateBatchOrder(ctx context.Context, in *order.BatchOrderRequest) (*order.BatchOrderResponse, error) {
	l := logic.NewCreateBatchOrderLogic(ctx, s.svcCtx)
	return l.CreateBatchOrder(in)
}
