// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: matching.proto

package server

import (
	"context"

	"github.com/tsfdsong/tradeengin/app/matching/internal/logic"
	"github.com/tsfdsong/tradeengin/app/matching/internal/svc"
	"github.com/tsfdsong/tradeengin/app/matching/match"
)

type MatchServiceServer struct {
	svcCtx *svc.ServiceContext
	match.UnimplementedMatchServiceServer
}

func NewMatchServiceServer(svcCtx *svc.ServiceContext) *MatchServiceServer {
	return &MatchServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MatchServiceServer) ProcessOrder(ctx context.Context, in *match.Order) (*match.MatchResult, error) {
	l := logic.NewProcessOrderLogic(ctx, s.svcCtx)
	return l.ProcessOrder(in)
}

func (s *MatchServiceServer) GetOrderBook(ctx context.Context, in *match.OrderBookRequest) (*match.OrderBookSnapshot, error) {
	l := logic.NewGetOrderBookLogic(ctx, s.svcCtx)
	return l.GetOrderBook(in)
}
