// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"github.com/tsfdsong/tradeengin/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Metrics},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/order",
					Handler: createOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/order/batch",
					Handler: createBatchOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/orderbook/:symbol",
					Handler: getOrderBookHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/metrics",
					Handler: metricsHandler(serverCtx),
				},
			}...,
		),
	)
}
