// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type BatchOrderReq struct {
	Orders []OrderReq `json:"orders"`
}

type BatchOrderResp struct {
	Results []OrderResp `json:"results"`
}

type OrderBookReq struct {
	Symbol string `path:"symbol"`
	Depth  int    `form:"depth,optional,default=20"`
}

type OrderBookResp struct {
	Symbol string       `json:"symbol"`
	Bids   []PriceLevel `json:"bids"`
	Asks   []PriceLevel `json:"asks"`
	Time   int64        `json:"time"`
}

type OrderReq struct {
	Symbol   string  `json:"symbol"`
	Price    float64 `json:"price"`
	Quantity int64   `json:"quantity"`
	Side     int8    `json:"side"`
	Type     int8    `json:"type"`
	ClientID string  `json:"clientId"`
}

type OrderResp struct {
	OrderID   uint64 `json:"orderId"`
	Status    int8   `json:"status"`
	Timestamp int64  `json:"timestamp"`
}

type PriceLevel struct {
	Price    float64 `json:"price"`
	Quantity int64   `json:"quantity"`
	Count    int     `json:"count"`
}
